name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
        if: ${{ always() }}
      - run: npm run test:unit
        if: ${{ always() }}
      - run: npm run test:coverage
        if: ${{ always() }}
      #- run: npm run test:coveralls
      # if: ${{ always() }}

      - name: Coveralls
        uses: coverallsapp/github-action@master
        if: ${{ always() }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
